# AzuraCast Docs build process
# Powered by Netlify

[build]
  publish = "public"
  command = "yarn build"

[[redirects]]
  from = "/install.html"
  to = "/install/index.html"
  status = 302

[[redirects]]
  from = "/api"
  to = "/api/index.html"
  status = 302

[[redirects]]
  from = "/demo"
  to = "/demo.html"
  status = 302

[[redirects]]
  from = "/slack"
  to = "https://join.slack.com/t/azuracast/shared_invite/enQtNDgyNzA4NzY2MzU3LTlkZjdhNjk3NWRkMWVmMzRhMjA3MDk1ZWMxOTQ0NjM4YWJhMWNiNDkwZTM3NjhkMTU1NzIwODgzNWY1NmNlMmU"
  status = 302